In [2]:
import numpy as np

In [3]:
list1 =[1,4,5,8]
type(list1)

list

In [4]:
print(np.__version__)

1.24.3


In [6]:
arr = np.array(list1)
arr

array([1, 4, 5, 8])

In [ ]:
list2=[1,3,5,"python"] #hetrogenous == home == string
arr1 = np.array(list2) #1,3,5 == int ,"python" == str
arr1,type(arr1)       #homegenous == str

In [7]:
arr1 = np.array([1,2,3,5])
arr1,type(arr1)

(array([1, 2, 3, 5]), numpy.ndarray)

# Data type array


In [11]:
arr1 = np.array((1,2,3,5))
arr1,type(arr1)

(array([1, 2, 3, 5]), numpy.ndarray)

In [ ]:
list1=[1,3,4,5,6]
arr2 = np.array
float to int, complex,str
complex to string


In [13]:
array1 = np.array([1,4,5,7,0.3],dtype= 'float')
array1 , array1.dtype

(array([1. , 4. , 5. , 7. , 0.3]), dtype('float64'))